### ISSUE TITLE
chore: few important doubts

### ISSUE THREAD

**Issue by Anmol-Baranwal** [spyder-ide/action-close-duplicate-issues#35]
- How does this actually works?

Will it check for same title in the issue or how many words will it check?

- What if I change the title later on, will this workflow run? We will have to trigger it, I guess.

- I'm looking for workflow to close issues created by same author.
Like, first is fine but whenever he/she creates another then it is closed automatically unless the PR is merged or the existing issue is closed.

**Comment by ccordoba12** [comment]
Hey @Anmol-Baranwal, this action looks for a pattern in the text of the issue description. So, I think it wouldn't work for what you want to do.

**Comment by Anmol-Baranwal** [comment]
@ccordoba12 
Thanks for letting me know. I'm closing this.
