### ISSUE TITLE
[Question] - dynamic patterns to determined by the current open and closed issues.

### ISSUE THREAD

**Issue by dinbtechit** [spyder-ide/action-close-duplicate-issues#36]
Can we check if there is already an existing issue with the same question or topic and mark it as a duplicate based on that?

**Comment by ccordoba12** [comment]
No, that's not possible with this action. You need to set in advance the patterns it is going to look for to close them in your workflow.

**Comment by dinbtechit** [comment]
@ccordoba12  - Thank you for the response. Closing this issue!
